# Site settings
title: Another hot day in ATX
email: zaxxon77@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog documenting a few tidbits of life here in ATX.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 2oldForThisHit
github_username:  zaxxon77

# Build settings
markdown: kramdown

